# Generated by Django 5.0.4 on 2024-05-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSearch_app', '0002_alter_userprofile_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
