# Generated by Django 5.0.4 on 2024-05-05 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSearch_app', '0003_worktype'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='JobSearch_app.category'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='JobSearch_app.worktype'),
        ),
    ]
