# Generated by Django 5.0.4 on 2024-05-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSearch_app', '0003_userprofile_first_name_userprofile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='customuser',
            name='specialty',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
