# Generated by Django 5.0.4 on 2024-05-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSearch_app', '0004_customuser_birth_date_customuser_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
    ]
