# Generated by Django 5.0.4 on 2024-05-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSearch_app', '0005_customuser_is_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company_address',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='customuser',
            name='industry',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
